config/routes.rb
Rails.application.routes.draw do

   
  match 'auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post] 
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post] 
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  get '/cleanup/' , :to => 'session#cleanup', :as => :cleanup
  
  resources :polls
    get '/polls/:id/edit' => 'polls#edit'

    patch '/polls/:id' => 'polls#update'

    delete '/polls/:id' => 'polls#destroy'

  
  resources :users 
  get 'dashboard/index', to: 'dashboard#index'
  get 'welcome/login', :as => :welcome_login
  root 'welcome#login'
  
  resources :votes, only: [:create]

  

  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :authorizations
    validates :username, :email, :presence => true
    has_many :votes, dependent: :destroy
    has_many :vote_options, through: :votes
 
 def self.create_with_omniauth info
     create!(username: info['name'],email: info['email'])
 end      
 
 def self.exists? info
    !!(User.find_with_omniauth(info))
 end     
 
 def self.find_with_omniauth info
     User.find_by(username: info['name'],email: info['email'])
 end
 
 def add_provider auth_hash
    self.authorizations.create_with_omniauth auth
 end
 
 def voted_for?(poll)
    votes.any? {|v| v.vote_option.poll == poll}
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/edit.html.haml
%h1= "Profile for #{@user.username}"
//%p Find me in app/views/users/edit.html.haml
//Create form to capture remaining user attributes and then send to update and in update update attributes and then go to dashboard and 
//in dashboard add an edit profile link

app/views/users/index.html.haml
// %h2 PollUpBing
// %p PollupBing is a webpage that shows all the events which are about to take place in Binghamton University. Users can register for events and participate in the poll questions and can ask questions regarding events. Results of the poll questions are posted when a user makes a choice.

// %form
//     %p Sign In
//     = label :user, :email, "Email"
//     = text_field :user, :email
//     = label :user, :password, "Password"
//     = password_field :user, :password
//     %input{:type => "submit", :value => "Sign in"}

// %p Not registered yet?
// %input{:type => "submit", :value => "Sign up"}
// = link_to "Forgot your password?", "sign_up_path"

%h1 Dashboard
= link_to 'Cleanup', cleanup_path

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml