config/routes.rb
Rails.application.routes.draw do

   
  match 'auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post] 
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post] 
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  get '/cleanup/' , :to => 'session#cleanup', :as => :cleanup
  
  resources :polls
    get '/polls/:id/edit' => 'polls#edit'

    patch '/polls/:id' => 'polls#update'

    delete '/polls/:id' => 'polls#destroy'

  
  resources :users 
  get 'dashboard/index', to: 'dashboard#index'
  get 'welcome/login', :as => :welcome_login
  root 'welcome#login'
  
  resources :votes, only: [:create]

  

  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
    has_many :vote_options, dependent: :destroy
    validates :topic, presence: true
    accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true
    
    def normalized_votes_for(option)
        votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
    end
    
    def votes_summary
        vote_options.inject(0) {|summary, option| summary + option.votes.count}
    end
    
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end
  
  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      flash[:success] = 'New poll was created successfully!'
      redirect_to dashboard_index_path
    else
      render 'new'
    end
  end


  def poll_params
    params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
  end
  
  def edit
    @poll = Poll.find(params[:id])
    render 'edit'
  end

  def update
    @poll = Poll.find(params[:id])
    if @poll.update(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to dashboard_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = 'Poll was destroyed!'
    else
      flash[:warning] = 'Error destroying poll...'
    end
    redirect_to dashboard_index_path
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_votes_for(option)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/views/polls/_vote_option.html.haml
.form-group
  = content_tag(:label) do
    - unless current_user.voted_for?(@poll)
      = radio_button_tag 'vote_option[id]', option.id
    = option.title
  = visualize_votes_for option

app/views/polls/_vote_option_fields.html.haml
.nested-fields
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', required: true
  = link_to_remove_association "remove option", f

app/views/polls/_voting_form.html.haml
= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do
  = hidden_field_tag 'poll[id]', @poll.id
  = render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option
  %p
    %b
      Total votes: #{@poll.votes_summary}
  - if current_user.voted_for?(@poll)
    %p You have already voted!
  - else
    = submit_tag 'Vote', class: 'btn btn-lg btn-primary'

%h3= link_to 'Back', dashboard_index_path, class: 'btn btn-default'

app/views/polls/edit.html.haml
- content_for(:page_header) {"Edit poll"}
= render 'shared/form', button_name: 'Save'

%h3= link_to 'Back', dashboard_index_path, class: 'btn btn-default'

app/views/polls/index.html.haml
- content_for(:page_header) {"Participate in our polls right now!"}

app/views/polls/new.html.haml
- content_for(:page_header) {"Create a new poll"}
= render 'shared/form', button_name: 'Create'

%h3= link_to 'Back', dashboard_index_path, class: 'btn btn-default'

app/views/polls/show.html.haml
- content_for(:page_header) {"Share your opinion"}
%h2= @poll.topic
= render 'voting_form'

%script{"data-turbolinks-track" => "true"}
  :cdata
    $(document).ready(function() {
    var voting_form = $('#voting_form');
    voting_form.validate({
    focusInvalid: false,
    errorClass: 'alert alert-warning',
    errorElement: "div",
    errorPlacement: function(error, element) { voting_form.before(error); },
    rules: {
    'vote_option[id]': {
    required: true
    }
    },
    messages: {
    'vote_option[id]': {
    required: "Please select one of the options."
    }
    }
    });
    });